adds fonticons
mrozbarry/hyper-beats pull request #14
Opened 2018-02-03 21:11 UTC by FrankyFrankFrank

brings in fontawesome through their cdn
uses the icons for:
- play
- pause
- add track
- delete track

2018-02-04 00:20 UTC, mrozbarry commented
I was sort of surprised that the font awesome npm module wasn't used, but at the same time, it looks like the npm module might only support fa 4.x and not 5.x.

2018-02-04 00:24 UTC, mrozbarry requested changes
Just a few self closing tags.

Not sure how I feel about the play/pause buttons - maybe bigger, but you'd have a better eye for that than me.

2018-02-04 00:24 UTC, mrozbarry commented on src/index.js
> +          {state.playing && <button class="button button-default" onclick={() => actions.suspend()}><i class="fas fa-pause"></i></button>}
We could probably bump these up in size, since these are _probably_ the most prominent actions on the page.

2018-02-04 00:24 UTC, mrozbarry commented on src/index.js
> +          <button class="button button-default" onclick={() => actions.addTrack()}><i class="fas fa-plus"></i> Add Track</button>
You can just use the good old self-closing tag `<i class="fas fa-plus" />`.

2018-02-04 00:24 UTC, mrozbarry commented on src/index.js
> +          {state.playing && <button class="button button-default" onclick={() => actions.suspend()}><i class="fas fa-pause"></i></button>}
Also self-closing tags :)

2018-02-04 00:24 UTC, mrozbarry commented on src/index.scss
> +  font-family: "niveau-grotesk",sans-serif;
Ooh, fancy :godmode:

2018-02-04 00:24 UTC, mrozbarry commented on src/TrackConfig.js
> -        &times;
Dat self closing tag, tho.

2018-02-04 00:26 UTC, mrozbarry commented
Also, no gif?!? I'm shocked!

![](https://media0.giphy.com/media/3eQ2cwRO11JGo/giphy.gif)

2018-02-04 03:00 UTC, FrankyFrankFrank commented
I like your style, man lol

I'll work on these changes probably tomorrow - thanks for the review!

2018-02-05 00:49 UTC, FrankyFrankFrank commented on src/index.js
> +          {state.playing && <button class="button button-default" onclick={() => actions.suspend()}><i class="fas fa-pause"></i></button>}
@mrozbarry I think I agree so I'll add that and let you see

2018-02-05 00:50 UTC, closed without merging